sheetname: Travel-Shuttle
levels:
  - floor: 1
    navette:
      - name: "N1111"
        ip: "10.136.17.11"
        row: "6"
      - name: "N1211"
        ip: "10.136.17.16"
        row: "8"
      - name: "N2111"
        ip: "10.136.17.31"
        row: "10"
      - name: "N2211"
        ip: "10.136.17.36"
        row: "12"
      - name: "N3111"
        ip: "10.136.17.51"
        row: "14"
      - name: "N3211"
        ip: "10.136.17.56"
        row: "16"
      - name: "N4111"
        ip: "10.136.17.71"
        row: "18"
      - name: "N4211"
        ip: "10.136.17.76"
        row: "20"
      - name: "N5111"
        ip: "10.136.17.91"
        row: "22"
      - name: "N5211"
        ip: "10.136.17.96"
        row: "24"
      - name: "N6111"
        ip: "10.136.17.111"
        row: "26"
      - name: "N6211"
        ip: "10.136.17.116"
        row: "28"

  - floor: 2
    navette:
      - name: "N1112"
        ip: "10.136.17.12"
        row: "31"
      - name: "N1212"
        ip: "10.136.17.17"
        row: "33"
      - name: "N2112"
        ip: "10.136.17.32"
        row: "35"
      - name: "N2212"
        ip: "10.136.17.37"
        row: "37"
      - name: "N3112"
        ip: "10.136.17.52"
        row: "39"
      - name: "N3212"
        ip: "10.136.17.57"
        row: "41"
      - name: "N4112"
        ip: "10.136.17.72"
        row: "43"
      - name: "N4212"
        ip: "10.136.17.77"
        row: "45"
      - name: "N5112"
        ip: "10.136.17.92"
        row: "47"
      - name: "N5212"
        ip: "10.136.17.97"
        row: "49"
      - name: "N6112"
        ip: "10.136.17.112"
        row: "51"
      - name: "N6212"
        ip: "10.136.17.117"
        row: "53"

  - floor: 3
    navette:
      - name: "N1113"
        ip: "10.136.17.13"
        row: "56"
      - name: "N1213"
        ip: "10.136.17.18"
        row: "58"
      - name: "N2113"
        ip: "10.136.17.33"
        row: "60"
      - name: "N2213"
        ip: "10.136.17.38"
        row: "62"
      - name: "N3113"
        ip: "10.136.17.53"
        row: "64"
      - name: "N3213"
        ip: "10.136.17.58"
        row: "66"
      - name: "N4113"
        ip: "10.136.17.73"
        row: "68"
      - name: "N4213"
        ip: "10.136.17.78"
        row: "70"
      - name: "N5113"
        ip: "10.136.17.93"
        row: "72"
      - name: "N5213"
        ip: "10.136.17.98"
        row: "74"
      - name: "N6113"
        ip: "10.136.17.113"
        row: "76"
      - name: "N6213"
        ip: "10.136.17.118"
        row: "78"

  - floor: 4
    navette:
      - name: "N1114"
        ip: "10.136.17.14"
        row: "81"
      - name: "N1214"
        ip: "10.136.17.19"
        row: "83"
      - name: "N2114"
        ip: "10.136.17.34"
        row: "85"
      - name: "N2214"
        ip: "10.136.17.39"
        row: "87"
      - name: "N3114"
        ip: "10.136.17.54"
        row: "89"
      - name: "N3214"
        ip: "10.136.17.59"
        row: "91"
      - name: "N4114"
        ip: "10.136.17.74"
        row: "93"
      - name: "N4214"
        ip: "10.136.17.79"
        row: "95"
      - name: "N5114"
        ip: "10.136.17.94"
        row: "97"
      - name: "N5214"
        ip: "10.136.17.99"
        row: "99"
      - name: "N6114"
        ip: "10.136.17.114"
        row: "101"
      - name: "N6214"
        ip: "10.136.17.119"
        row: "103"
