// Package models contains the types for schema ''.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// ShoeTravel represents a row from 'shoe_travel'.
type ShoeTravel struct {
	T1Shuttle     sql.NullString `json:"t1_shuttle"`     // t1_shuttle
	T1Distance    sql.NullInt64  `json:"t1_distance"`    // t1_distance
	T2Distance    sql.NullString `json:"t2_distance"`    // t2_distance
	ShoeTravel    sql.NullString `json:"shoe_travel"`    // shoe_travel
	T1Timestamp   sql.NullString `json:"t1_timestamp"`   // t1_timestamp
	T2Timestamp   sql.NullString `json:"t2_timestamp"`   // t2_timestamp
	DaysInstalled sql.NullString `json:"days_installed"` // days_installed
	Notes         sql.NullString `json:"notes"`          // notes
	UUID          sql.NullString `json:"uuid"`           // uuid
}
